name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '18.x'
        description: 'Node.js version to use'
      run-tests:
        required: false
        type: boolean
        default: true
        description: 'Whether to run tests'
    secrets:
      NPM_TOKEN:
        required: false
        description: 'NPM token for package installation'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Build
        run: npm run build --if-present
      
      - name: Run tests
        if: ${{ inputs.run-tests }}
        run: npm test
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 7 